// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEaB0MvrYSQGmTpKPz-FLU9xaogIjfnZQ',
    appId: '1:733447678161:web:012f2120e226a52e9bbdf0',
    messagingSenderId: '733447678161',
    projectId: 'timetableoptimizer',
    authDomain: 'timetableoptimizer.firebaseapp.com',
    storageBucket: 'timetableoptimizer.firebasestorage.app',
    measurementId: 'G-9C7G566BKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNM90OPwK28YNvHg3GRp4NpSy8uRCmJRg',
    appId: '1:733447678161:android:3be79f90f1c842239bbdf0',
    messagingSenderId: '733447678161',
    projectId: 'timetableoptimizer',
    storageBucket: 'timetableoptimizer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-3wzDTB4x6qREb0NIVZ7L02ZMibGCro0',
    appId: '1:733447678161:ios:4f33cb9568bcd3409bbdf0',
    messagingSenderId: '733447678161',
    projectId: 'timetableoptimizer',
    storageBucket: 'timetableoptimizer.firebasestorage.app',
    iosBundleId: 'com.raisin.collaborativeTimetableOptimizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEaB0MvrYSQGmTpKPz-FLU9xaogIjfnZQ',
    appId: '1:733447678161:web:73155f2ef92143259bbdf0',
    messagingSenderId: '733447678161',
    projectId: 'timetableoptimizer',
    authDomain: 'timetableoptimizer.firebaseapp.com',
    storageBucket: 'timetableoptimizer.firebasestorage.app',
    measurementId: 'G-E0N41P6KQP',
  );
}
